services:
  web:
    env_file:
     - .env
    restart: always
    image: lcbruit/identity_web:latest
    expose:
      - "${PORT}"
    ports:
      - "${PORT}:8080"
    volumes:
      - "${DATA_DIRECTORY}:/uploads"
  worker:
    env_file:
     - .env
    restart: always
    image: lcbruit/identity_celery:latest
    command: worker
    volumes:
      - "${DATA_DIRECTORY}:/uploads"
  beat:
    env_file:
     - .env
    restart: always
    image: lcbruit/identity_celery:latest
    command: beat --pidfile=
    volumes:
      - "${DATA_DIRECTORY}:/uploads"
  