version: '2'

services:
  web:
    env_file:
     - .env
    restart: always
    build: ./web
    expose:
      - "${PORT}"
    ports:
      - "${PORT}:8000"
    command: /usr/local/bin/gunicorn --log-file=- --capture-output --config gunicorn.conf -w 2 -b :8000 live:application
    volumes:
      - "${DATA_DIRECTORY}:/uploads"
  worker:
    env_file:
     - .env
    restart: always
    build: ./worker
    command: celery -A celery_worker.celery worker
    volumes:
      - "${DATA_DIRECTORY}:/uploads"
  beat:
    env_file:
     - .env
    restart: always
    build: ./worker
    command: celery --pidfile= -A celery_worker.celery beat
    volumes:
      - "${DATA_DIRECTORY}:/uploads"
